services:
  - type: web
    name: rajasthan-tourism-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: GEMINI_API_KEY
        value: your_gemini_api_key
